### ISSUE TITLE
localhost/drive not found

### ISSUE THREAD

**Issue by hunter6399** [RyanZotti/Self-Driving-Car#133]
![2020-02-18-165404_1600x900_scrot](https://user-images.githubusercontent.com/36127367/74733605-ae2aa080-5272-11ea-8066-5c94b182dd1e.png)

_only works on pi_ 

I'm using L298N dual driver is this the problem?(right now ENA,INA1,INA2,INB1.INB2.ENB are connected to 16,18,22,19,21,23)
Also, save_streaming_data.py only works when pi is connected via an HDMI to a monitor on remote execution(SSH) I get 
**_: cannot connect to X server_**
_(Assuming this is GUI problem)_

Edit : on changing the port from 8090 to 81 results  to following 

> drive_api.py:151: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
>   GPIO.setup(self.pinForward, GPIO.OUT)
> drive_api.py:152: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
>   GPIO.setup(self.pinBackward, GPIO.OUT)
> drive_api.py:153: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
>   GPIO.setup(self.pinControlStraight, GPIO.OUT)
> drive_api.py:155: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
>   GPIO.setup(self.pinLeft, GPIO.OUT)
> drive_api.py:156: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
>   GPIO.setup(self.pinRight, GPIO.OUT)
> drive_api.py:157: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
>   GPIO.setup(self.pinControlSteering, GPIO.OUT)
> Traceback (most recent call last):
>   File "drive_api.py", line 238, in <module>
>     app.listen(81)
>   File "/usr/lib/python3/dist-packages/tornado/web.py", line 2042, in listen
>     server.listen(port, address)
>   File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 143, in listen
>     sockets = bind_sockets(port, address=address)
>   File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 168, in bind_sockets
>     sock.bind(sockaddr)
> OSError: [Errno 98] Address already in use

 

>

**Comment by hunter6399** [comment]
using different ports for ffmpeg(8090) and a different port for drive_api(81) worked just fine.
