### ISSUE TITLE
Dataprep error

### ISSUE THREAD

**Issue by hunter6399** [RyanZotti/Self-Driving-Car#134]
I'm trying to reproduce the training process 
I have saved all the training files in ~/Self-Driving-Car/data

When I run Save-all_runs_as_numpy.py
I get the following error 

`Started work on clean_session.txt
b'/home/hunter/Self-Driving-Car/data/clean_session.txt'
Traceback (most recent call last):
  File "save_all_runs_as_numpy_files.py", line 29, in <module>
    predictors, targets = process_session(data_path, gamma_map, rgb)
  File "/home/hunter/Self-Driving-Car/dataprep.py", line 128, in process_session
    gamma_image = adjust_gamma(frame, gamma_table)
  File "/home/hunter/Self-Driving-Car/dataprep.py", line 23, in adjust_gamma
    return cv2.LUT(image, table)

cv2.error: OpenCV(4.2.0) /io/opencv/modules/core/src/matrix.cpp:406: error: (-215:Assertion failed) m.dims >= 2 in function 'Mat'`

The opencv window pops up and closes with this error.

**Comment by hunter6399** [comment]
it was because the video timestamps did not match the clean session time stamps . After Cleaning the data the script works just fine.
